#!/usr/bin/env bash

# example usage:
# every 60 my-command.sh
#
# executes my-command.sh every 60 seconds

function show_help() {
  echo "Example usage:"
  echo "every 60 my-command.sh"
  echo ""
  echo "This executes my-command.sh every 60 seconds"
}

if [ -z "$1" ]; then
  show_help
  exit 1
fi

if [ -z "$2" ]; then
  show_help
  exit 1
fi

while true; do
  $2
  sleep $1
done
