#!/usr/bin/env bash

# read wallpaperrc
RC_FILE=$HOME/.wallpaperrc

# if file isnt found, fall back to default folder + interval
if [ ! -f "$RC_FILE" ]; then
  echo "no wallpaper config found, enabling default wallpapers..."
  $HOME/.scripts/switch-wallpapers default 60
fi

# read wallpaper folder from config file
WALLPAPER_DIR=$(cat $RC_FILE | cut -d ":" -f 1)
echo "folder: $WALLPAPER_DIR"

# get wallpaper interval
INTERVAL=$($HOME/.scripts/wallpaper-interval)
echo "interval: $INTERVAL"

# write config file?

# get random wallpaper
WALLPAPER=$(find $WALLPAPER_DIR -type f | shuf -n 1)

# set new wallpaper
$HOME/.scripts/wallpaper "$WALLPAPER"

exit 0
