#!/usr/bin/env bash

# Script config
# TRANSITION_TYPE="random"
TRANSITION_TYPE="simple"
TRANSITION_FPS=12
TRANSITION_STEP=20
THEME_SATURATION=0.5 # 0.0-1.0

# read wallpaperrc
RC_FILE=$HOME/.wallpaperrc

echo "setting new wallpaper..."

# if file isnt found, fall back to default folder + interval
if [ ! -f "$RC_FILE" ]; then
  echo "no wallpaper config found, enabling default wallpapers..."
  $HOME/.scripts/switch-wallpapers default 60
fi

# read wallpaper folder from config file
WALLPAPER_DIR=$(cat $RC_FILE | cut -d ":" -f 1)
echo "folder: $WALLPAPER_DIR"

# get wallpaper interval
INTERVAL=$($HOME/.scripts/wallpaper-interval)
echo "interval: $INTERVAL"

# write config file?

WALLPAPER=$(find $WALLPAPER_DIR -type f | shuf -n 1)

# echo "new paper: $WALLPAPER"

# set wallpaper, refresh theme, restart apps
wal --saturate $THEME_SATURATION -i "$WALLPAPER" >/dev/null 2>&1 # create color scheme

swww img "$WALLPAPER" \
  --transition-step $TRANSITION_STEP \
  --transition-fps $TRANSITION_FPS \
  --transition-type $TRANSITION_TYPE >/dev/null 2>&1 # set wallpaper

pkill -SIGUSR2 waybar      # reload waybar config
swaync-client --reload-css # reload notification center

exit 0
