#!/usr/bin/env bash

# this script writes the wallpaper directory and interval to ~/.wallpaperrc
# and sets a new wallpaper instantly

if [ -z "$2" ]; then
  INTERVAL=60
else
  # TODO: if interval is set, check if it is actually a number
  INTERVAL=$2
fi

case $1 in
"all")
  echo "$HOME/Pictures/Wallpapers/Landscape:$INTERVAL" >$HOME/.wallpaperrc
  ;;

"safe" | "default")
  echo "$HOME/Pictures/Wallpapers/Landscape/default:$INTERVAL" >$HOME/.wallpaperrc
  ;;

"unsafe" | "private")
  echo "$HOME/Pictures/Wallpapers/Landscape/private:$INTERVAL" >$HOME/.wallpaperrc
  ;;

*)
  echo "Usage: $(basename $0) <all|default|private> <refresh interval in seconds>"
  exit 0
  ;;
esac

$HOME/.scripts/set-wallpaper

exit 0
