#!/usr/bin/env bash

WALLPAPER=$1

# Script config
# TRANSITION_TYPE="random"
TRANSITION_TYPE="simple"
TRANSITION_FPS=12
TRANSITION_STEP=20
THEME_SATURATION=0.4 # 0.0-1.0

echo "setting new wallpaper..."
echo $WALLPAPER

# write wallpaper to cache for hyprlock - warning: spaces in the filename will break hyprlock background
# check hyprlock.conf for more details
echo "\$wallpaper = $WALLPAPER" >$HOME/.cache/hyprland/hyprlock-wallpaper

# set wallpaper, refresh theme, restart apps
wal --saturate $THEME_SATURATION -i "$WALLPAPER" >/dev/null 2>&1 # create color scheme

swww img "$WALLPAPER" \
  --transition-step $TRANSITION_STEP \
  --transition-fps $TRANSITION_FPS \
  --transition-type $TRANSITION_TYPE >/dev/null 2>&1 # set wallpaper

# these would be better methods for reloading waybar
# but other apps crash randomly when using these
# i don't know why

# hyprctl dispatch exec pkill -SIGUSR2 waybar

# pkill -SIGUSR2 waybar      # reload waybar config
# kill -s USR2 $(pgrep -f waybar)

# pkill -USR2 waybar

kill -9 $(pidof waybar)  # kill waybar
waybar >/dev/null 2>&1 & # start waybar

swaync-client --reload-css # reload notification center

exit 0
