#!/usr/bin/env bash

# script for screen recording
# it starts a recording on the first call and will terminate it on the second call
# records full screen by default
# pass -s flag to select a screen area to record

RECORDING_DIR=~/Videos/Recordings
RECORDING_FILE="$RECORDING_DIR/Recording-$(date +"%Y-%m-%d--%H-%M-%S").mp4"
SCREEN="eDP-1" # internal display

if [ -z $(pgrep wf-recorder) ]; then
  # record selection
  if [ "$1" == "-s" ]; then
    rect=$(slurp -c "#FFFFFF")
    notify-send "Recording selected area" --icon=media-record
    wf-recorder -o $SCREEN -f $RECORDING_FILE -a -g "$rect" >/dev/null 2>&1 &

  # record screen
  else
    notify-send "Recording screen" --icon=media-record
    wf-recorder -o $SCREEN -f $RECORDING_FILE -a >/dev/null 2>&1 &
  fi
else
  killall -s SIGINT wf-recorder
  notify-send "Recording complete" --icon=media-playback-stop
  while [ ! -z $(pgrep -x wf-recorder) ]; do wait; done
fi
