#!/usr/bin/env bash

# this script writes the wallpaper directory and interval to ~/.cache/wallpaper.config
# and sets a new wallpaper instantly

CONFIG_FILE=$HOME/.cache/wallpaper-config

if [ -z "$2" ]; then
  INTERVAL=60
else
  # TODO: if interval is set, check if it is actually a number
  INTERVAL=$2
fi

case $1 in
"all")
  echo "$HOME/Pictures/Wallpapers/Landscape:$INTERVAL" >$CONFIG_FILE
  ;;

"safe" | "default")
  echo "$HOME/Pictures/Wallpapers/Landscape/default:$INTERVAL" >$CONFIG_FILE
  ;;

"unsafe" | "private")
  echo "$HOME/Pictures/Wallpapers/Landscape/private:$INTERVAL" >$CONFIG_FILE
  ;;

*)
  echo "Usage: $(basename $0) <all|default|private> <refresh interval in seconds>"
  exit 0
  ;;
esac

kill -s USR1 $(pgrep -f endless-wallpaper-loop.sh)

exit 0
